- README.md
- examples/ThreeD_TaylorGreenVortex.jl
- examples/ThreeD_donut.jl
- examples/TwoD_Julia.jl
- examples/TwoD_SmoothLivePlot.jl
- examples/TwoD_block.jl
- examples/TwoD_circle.jl
- examples/TwoD_plots.jl
- src/AutoBody.jl
- src/Body.jl
- src/Flow.jl
- src/MultiLevelPoisson.jl
- src/Poisson.jl
- src/WaterLily.jl
- src/util.jl
- test/runtests.jl
Implementation of second order BDIM required defining a `AbstractBody` type, and a better `Simulation` constructor, in addition to the changes to the flow solver.
> Second Order BDIM and general overhaul

- examples/ThreeD_TaylorGreenVortex.jl
- examples/TwoD_Julia.jl
Thanks for sharing these examples !
A quick fix for the following error:
```julia
$ julia examples/TwoD_Julia.jl
ERROR: LoadError: MethodError: no method matching +(::Vector{ComplexF64}, ::ComplexF64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
+(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
+(::Base.TwicePrecision, ::Number) at twiceprecision.jl:267
+(::ChainRulesCore.Composite{P, T} where T, ::P) where P at [...]/ChainRulesCore/NR7YR/src/differential_arithmetic.jl:184
...
```
> Fix running examples on julia >=1.6.1

- docs/make.jl
Closes #20 
This PR updates the Documenter.jl script to point to the new URL for the repo.
> Fix: Update repo URL in docs to `https://github.com/weymouth/WaterLily.jl`

- docs/make.jl
> Fix "link to source" buttons in docs by removing `repo` from makedocs

- src/AutoBody.jl
- src/WaterLily.jl
This function takes as input a list of SVectors containing the sdf and the map for every body to add to the simulation. The output is an Autobody that can directly be used as input in the Simulation function.
Example of three bodies generated with only two function of generation (shows the sdf(x,t)):
> add function addBody

- .gitignore
- CUDAEnv/bcs.jl
- Project.toml
Kernel example for the implementation of boundary condition for a `D`-dimensional `Flow`. Also added the new dependencies for the programming of the kernel and included the `.vscode` directory in `.gitignore`.
Still, feel free to ignore the last two points, as we might want to do that later on.
> Boundary conditions kernel and dependencies

- CUDAEnv/Flow.jl
- CUDAEnv/bcs.jl
- src/util.jl
Flow.jl self-contained example. Also included in utils.jl the necessary functions to get new `Flow` working (commented out for the moment). Small improvements on bcs.jl in this sense too.
In `Flow`, `apply!(uλ, u)` still needs to be adapted.
> Flow.jl MWE

- .gitignore
- CUDAEnv/Flow.jl
- CUDAEnv/poisson.jl
- src/Flow.jl
- src/WaterLily.jl
- src/util.jl
- test/runtests.jl
Started porting Flow.jl using KernelAbstractions.jl.
Currently, `@loop` calls in `conv_diff!` need to be revised. Some calls such as `a[I] += ...` need to be expanded as `a[I] = a[I] + ...`. The `@loop ... inside_u(...)` calls need to be replaced by `@inside`. Even when applying these changes, errors still arise so I guess the new macros will need to be adapted for this.
> Started porting Flow.jl using KernelAbstractions.jl [WIP]

- .gitignore
- Project.toml
- benchmark/donut/donut.jl
- benchmark/donut/donut_master.jl
- benchmark/mom_step/Project.toml
- benchmark/mom_step/mom_step.jl
- benchmark/mom_step/mom_step_master.jl
- benchmark/tgv/tgv.jl
- benchmark/tgv/tgv_master.jl
- src/util.jl
Added mom_step.jl benchmark, also for the master branch. Remember to set threads to 1 when running on master for the baseline.
> mom_step benchmark

- src/util.jl
I noticed that `@inline` had to be used in https://github.com/weymouth/WaterLily.jl/blob/28b5a383374486a4b68ad9cac9d81c379cab35c3/src/util.jl#L13
for the GPU code to compile, differently from CPU where this was not needed.
I rose this issue https://github.com/JuliaGPU/KernelAbstractions.jl/issues/392 and it was pointed out that `δ(d,I::CartesianIndex{N})` was type-unstable. This fix makes it type-stable.
> delta function for CI was not type-stable

- docs/Project.toml
- docs/make.jl
- src/AutoBody.jl
- src/Body.jl
- src/Metrics.jl
- src/Poisson.jl
- src/WaterLily.jl
- src/util.jl
This PR fixes some more typos and rendering issues in the docstrings.
Also, it uses Documenter v0.27 + MathJax3.
(Was there any particular reason Documenter was pinned to v0.24? If so, then I can revert that...)
> Use Documenter v0.27

- src/Flow.jl
- src/util.jl
Rescales the source term and solution field such that the solver tolerance directly reflects the divergence in the projected velocity field. This also tends to reduce the effort required to project the correction step.
> Rescale source term

- .gitignore
- Project.toml
- examples/TwoD_circle_vtk.jl
- src/WaterLily.jl
- src/vtkWriter.jl
Allows to export `WaterLily` simulations to `.vti` (image) grid.
The `vtkWriter` structure holds the `pvd` collection name, and some attributes `attrib::Dict{String, Function}` that maps a `vtk` variable to a function that extracts it from a `Simulation`. For example, to export the "Velocity" and "Pressure" fields the attributes will be
```julia
attrib = Dict("Velocity" => velocity(a::Simulation)=a.flow.u, 
"Pressure" => pressure(a::Simulation)=a.flow.p)
``` 
This allows exporting arbitrary scalar, vector, and tensor fields to `vtk`. A more complex example would be to export the z-component of the vorticity with
```julia
attrib = Dict("Vorticity_Z" => vorticity_Z(a::Simulation)=
(@inside a.flow.σ[I] = WaterLily.curl(3,I,a.flow.u)*a.L/a.U;
a.flow.σ))
```
An example of this is provided in …
> add vtkWriter to WaterLily

- examples/TwoD_circle_periodicBC_convectiveBC.jl
- src/Body.jl
- src/Flow.jl
- src/MultiLevelPoisson.jl
- src/Poisson.jl
- src/WaterLily.jl
- src/util.jl
- test/runtests.jl
Implementation of periodic boundary conditions together with the convective exit.
There is an example [examples/TwoD_circle_periodicBC_convectiveBC.jl](file) that runs a y-periodic flow with a convective exit. The circle moves in the y-direction and crosses the boundary. This shows how to set up a periodic sdf.
I have added tests to check that the correct behavior is obtained for the boundary condition, for the different combinations of input.
I have not tested that the QUICK scheme implementation for periodic BC is correct, I just assumed it is based on @TzuYaoHuang simulations.
> Implement periodic boundary conditions

- src/WaterLily.jl
- test/runtests.jl
Change `sim_step!` to measure the body at `timeNext` instead of `time`. This means the flow and BC are both at `timeNext` at the end of the time step. The results are exactly the same, just one time step earlier. 
While cleaning up `sim_step!`, I also made it so calling the function without `t_end` does a single step, and added an accelerating body test case to check that the flow is synced to the body velocity.
> measure body at timeNext instead of time

- Project.toml
Unless I'm missing something, `Documenter` and `Test` aren't used in the package itself.
> Remove useless dependencies from Project.toml

- benchmark/benchmark.jl
- benchmark/benchmark.sh
- benchmark/util.jl
The script currently assumes the benchmarks are run in the `benchmark/` directory, but I don't see why it has to be the case.
> Make it possible to run the benchmarks outside of their directory

- benchmark/README.md
- benchmark/benchmark.jl
- benchmark/util.jl
- src/WaterLily.jl
Small benchmark fixes, and `sim_step!` can now be called more than one time and it will always perform additional `max_steps` steps (always up to `t_end` simulation time).
> Small fixes in benchmark and sim_step!

- README.md
- examples/TwoD_SlowStartCircle.jl
I realized that some of the solver's new capabilities are not well documented. I have updated the README.md with a few useful things.
> update README with solver upgrades

- .github/workflows/ci.yml
This PR runs the CI on Julia v1.10 (additionally to v1.9).
> Add CI for julia v1.10

- src/Metrics.jl
When calculating lambda2, `S^2+Ω^2` is not always guaranteed to be Hermitian due to floating point error. This will cause issue when calculating its eigen value, especially for MacOS system.
In this regards, forcing the matrix be Hermitian fixes the issue. Furthermore, this won't hurt the performance. I even see some gain in MacOS. You could run the following code several times.
```julia
using LinearAlgebra, StaticArrays, BenchmarkTools
a = @SMatrix rand(3,3)
traceA = tr(a)
b = a .- traceA # make it traceless
function λ₂old(J)
S,Ω = (J+J')/2,(J-J')/2; eigvals(S^2+Ω^2)[2]
end
function λ₂new(J)
S,Ω = (J+J')/2,(J-J')/2; eigvals(Hermitian(S^2+Ω^2))[2]
end
println("The one without Hermitian:")
@btime λ₂old($b)
println("The one with Hermitian:")
@btime λ₂new($b)
```
output (Fedora 39 with Intel …
> Fix the issue when calculating λ₂ by using Hermitian matrix

- src/util.jl
- test/runtests.jl
This adds the field interpolation routine that will be required for the `Parametricbodies.∮nds`
I also wrote a very simple test for the routine.
> add interp routine

- README.md
- docs/Project.toml
- docs/make.jl
- notebooks/Shark.jl
Should fix https://github.com/WaterLily-jl/WaterLily.jl/issues/138
> Fixed links to point to organisation url

- src/Body.jl
- src/Metrics.jl
- src/util.jl
- test/maintests.jl
When running on LUMI, I came across an error type on `measure`, where `loc` was being used without passing the type. I think in general we should always pass the type when calling `loc` so I have fixed this across the codebase.
Also, I came across a broadcasting problem on the AMD GPU in LUMI, where operation such as `a[i,:] .= ...` within a kernel are not allowed. To solve this I explicitly wrote the necessary loops in the `measure` function, and the only other place where broadcasting is used within a kernel is in https://github.com/WaterLily-jl/WaterLily.jl/blob/d23ac35501fbe77584bfdea1c05b6850b1239a1f/src/Metrics.jl#L98
So probably this would fail too. I will first check any performance regression for `measure` and if all is good we can rewrite the forces routines too.
> Fix measure type error on AMD GPU by passing type on loc function, and also fix broadcasting

- src/AutoBody.jl
- src/Body.jl
- src/Metrics.jl
- test/maintests.jl
We don't need normal or velocity measurements outside a very narrow band in the solver, so `measure(fast)` can be applied there as well, but the band is variable. Changed `fast=false` to `fastd²=Inf` and n,V are skipped when `d^2>fastd²`. 
Applied in `measure!(flow)` and tests passing, but I haven't benchmarked yet. Should be a bit faster for the Jelly and will _really_ speed up ParametricBody simulations.
> Use fast `measure(body)` in `measure!(flow)`

- README.md
The example repo is pretty easy to miss otherwise.  This is just a shields.io button, so it's pretty easy to configure!
> Add a button to view examples in the README

- ext/WaterLilyAMDGPUExt.jl
- ext/WaterLilyCUDAExt.jl
Scalar-indexing asserts on top-level had no impact and they are already the default option.
Closes https://github.com/WaterLily-jl/WaterLily.jl/issues/167.
> Removed scalar indexing asserts on GPU extensions

- src/Poisson.jl
We've been seeing a string of problems related to weird alpha,beta values in `pcg!`. This is typically because of an unsatisfiable residual being handed to the solver.
The best solution is to find the bad input! But making the solver a little more robust also seems like a good idea. Here, I've put a check that alpha is not to small OR TOO BIG.
> Added large alpha check

- ext/WaterLilyPlotsExt.jl
`flood` only accept CPU `Array`! Or else it cannot work with GPU simulation.
> Fix a small bug

- test/maintests.jl
Missing an `allowscalar` to pass test on GPU.
> Fixed Circle in accelerating flow on GPU test

- ext/WaterLilyPlotsExt.jl
There was still an issue with `flood(a::Array;kwargs...)` that prevented `CuArray` from being passed directly to the function, even though internally an `Array` conversion was made before passing to `contourf`.
Additionally, the `plot_logger` needs to be changed a bit to be used with Biot-Savart.
> Fix Array type in flood and plot_logger for Biot-Savart

- src/util.jl
- test/maintests.jl
- test/runtests.jl
This fixes the `interp(x::SVector, A::AbstractArray)` to work with Cartesian coordinates for `x` and not index coordinates.
> interp for Cartesian Coordinates

- src/Metrics.jl
`nds` is currently passed `x::SVector{n,To}` where `To` is the promoted _output_ type of the force. This doesn't make sense, and it breaks `nds` on GPUs when `body` has a different type.
> Fix force routine types

- .github/workflows/ci.yml
Also, only triggered when changes are detected on certain `paths`. I have implemented this base on the CI of[ Oceananigans.jl](https://github.com/CliMA/Oceananigans.jl/blob/main/.github/workflows/ci.yml) and [Trixi.jl](https://github.com/trixi-framework/Trixi.jl/blob/main/.github/workflows/ci.yml), which follow this same logic.
> CI now only triggered by PR or pushes on master

- ext/WaterLilyGLMakieExt.jl
Moved `display(fig)` at end of `viz!`. This allows to visualize a `sim::Simulation` even when `t_end` is not provided, or `t_end` is just `sim_time(sim)`. Need also to clean up `@assert`s.
> Small `viz!` improvements

- src/util.jl
- test/maintests.jl
The `interp` function still had an issue, which was dispatching to `Float64` by default when operating on vector arrays this was only breaking on GPUs; this was missed by the test. I'll try to determine the reason and add a test for this before we merge.
This is not the identical function that we have in `Pathlines.jl`.
> type error in interp

- src/AutoBody.jl
- src/Body.jl
- test/maintests.jl
Lazy construction of set operations on AbstractBodies. Combining the best of the old boolean operators (easy to use and work on GPUs) and Bodies struct (lazy construction means no memory blow up). Also applies to any AbstractBody, not just AutoBody. And all in 11 lines of code...
This PR also fixes a few inconsistencies in the AbstractBody interface. It supplies a default `sdf` function so extended type only have to supply `measure`. Of course, you can specialize on `sdf` if it would be helpful (like for AutoBodies). And NoBody was missing `measure` which would have thrown an error if people tried to `measure_sdf` of a default simulation. Now it gives d=Inf, which should be compatible with any other bodies.
I _might_ also modify the `measure!(::Flow)` function so we can create `SharpBody` …
> New SetBody struct

- ext/WaterLilyJLD2Ext.jl
- ext/WaterLilyMakieExt.jl
- src/Metrics.jl
- src/WaterLily.jl
- test/maintests.jl
Users should now call `update!(meanflow::MeanFlow,flow::Flow)` themselves to update the mean flow and second order statistics. This is motivated by the fact that we do not need to update them at every time step: this can be too expansive and unnecessary from the stats standpoint.
> Removed `meanflow` kwarg from `simstep!`, and other minor fixes in `MeanFlow`
